### ISSUE TITLE
FHIR Validation problem

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox#135]
NP exception with Bundle-2Doc-ChlamydiaTrachomatis.json

Validate ServiceRequest against http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-servicerequest-laboratory-order|1.0.0-trialuse.Validate ServiceRequest against http://hl7.eu/fhir/laboratory/StructureDefinition/ServiceRequest-eu-lab|current..........20..........40..........60..........80.........|
|
...2023-09-18 11:38:12.267 [http-nio-8080-exec-1] ERROR c.a.f.h.j.v.ValidationProvider [ValidationProvider.java:230] Unknown FHIRVersion code '0.0.13'
org.hl7.fhir.exceptions.FHIRException: Unknown FHIRVersion code '0.0.13'
        at org.hl7.fhir.r5.model.Enumerations$FHIRVersion.fromCode(Enumerations.java:12157)
        at org.hl7.fhir.r5.utils.XVerExtensionManager.makeDefinition(XVerExtensionManager.java:97)
        at org.hl7.fhir.validation.BaseValidator.xverDefn(BaseValidator.java:1105)
        at org.hl7.fhir.validation.BaseValidator.getXverExt(BaseValidator.java:1155)
        at org.hl7.fhir.validation.instance.InstanceValidator.checkExtension(InstanceValidator.java:1884)
        at org.hl7.fhir.validation.instance.InstanceValidator.checkChildByDefinition(InstanceValidator.java:5664)
        at org.hl7.fhir.validation.instance.InstanceValidator.checkChild(InstanceValidator.java:5491)
        at org.hl7.fhir.validation.instance.InstanceValidator.validateElement(InstanceValidator.java:5439)
        at org.hl7.fhir.validation.instance.InstanceValidator.startInner(InstanceValidator.java:5091)
        at org.hl7.fhir.validation.instance.InstanceValidator.start(InstanceValidator.java:4884)
        at org.hl7.fhir.validation.instance.InstanceValidator.validateResource(InstanceValidator.java:6347)
        at org.hl7.fhir.validation.instance.InstanceValidator.validateContains(InstanceValidator.java:5315)
        at org.hl7.fhir.validation.instance.InstanceValidator.checkChildByDefinition(InstanceValidator.java:5673)
        at org.hl7.fhir.validation.instance.InstanceValidator.checkChild(InstanceValidator.java:5491)
        at org.hl7.fhir.validation.instance.InstanceValidator.validateElement(InstanceValidator.java:5439)
        at org.hl7.fhir.validation.instance.InstanceValidator.checkChildByDefinition(InstanceValidator.java:5691)
        at org.hl7.fhir.validation.instance.InstanceValidator.checkChild(InstanceValidator.java:5491)
        at org.hl7.fhir.validation.instance.InstanceValidator.validateElement(InstanceValidator.java:5439)
        at org.hl7.fhir.validation.instance.InstanceValidator.startInner(InstanceValidator.java:5091)
        at org.hl7.fhir.validation.instance.InstanceValidator.start(InstanceValidator.java:4884)
        at org.hl7.fhir.validation.instance.InstanceValidator.validateResource(InstanceValidator.java:6347)
        at org.hl7.fhir.validation.instance.InstanceValidator.validate(InstanceValidator.java:908)
        at org.hl7.fhir.validation.instance.InstanceValidator.validate(InstanceValidator.java:742)
        at ch.ahdis.matchbox.engine.MatchboxEngine.validate(MatchboxEngine.java:450)
        at ch.ahdis.fhir.hapi.jpa.validation.ValidationProvider.validateWithResult(ValidationProvider.java:194)
        at ch.ahdis.fhir.hapi.jpa.validation.ValidationProvider.validate(ValidationProvider.java:184)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:264)
        at ca.uhn.fhir.rest.server.method.OperationMethodBinding.invokeServer(OperationMethodBinding.java:399)
        at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.doInvokeServer(BaseResourceReturningMethodBinding.java:146)
        at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.invokeServer(BaseResourceReturningMethodBinding.java:275)
        at ca.uhn.fhir.rest.server.method.OperationMethodBinding.invokeServer(OperationMethodBinding.java:356)
        at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:1190)
        at ch.ahdis.matchbox.MatchboxRestfulServer.handleRequest(MatchboxRestfulServer.java:33)
        at ca.uhn.fhir.rest.server.RestfulServer.doPost(RestfulServer.java:432)
        at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1921)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.springframework.web.servlet.resource.ResourceUrlEncodingFilter.doFilter(ResourceUrlEncodingFilter.java:67)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:768)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:1623)
2023-09-18 11:38:12.268 [http-nio-8080-exec-1] INFO  c.a.f.h.j.v.ValidationProvider [ValidationProvider.java:273] Validation time: 00:00:53.654
2023-09-18 11:38:12.276 [http-nio-8080-exec-1] ERROR c.u.f.r.s.i.ExceptionHandlingInterceptor [ExceptionHandlingInterceptor.java:198] Failure during REST processing
ca.uhn.fhir.rest.server.exceptions.InternalErrorException: HAPI-0389: Failed to call access method: java.lang.NullPointerException: Cannot invoke "ca.uhn.fhir.validation.ValidationResult.getMessages()" because "result" is null
        at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:272)
        at ca.uhn.fhir.rest.server.method.OperationMethodBinding.invokeServer(OperationMethodBinding.java:399)
        at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.doInvokeServer(BaseResourceReturningMethodBinding.java:146)
        at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.invokeServer(BaseResourceReturningMethodBinding.java:275)
        at ca.uhn.fhir.rest.server.method.OperationMethodBinding.invokeServer(OperationMethodBinding.java:356)
        at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:1190)
        at ch.ahdis.matchbox.MatchboxRestfulServer.handleRequest(MatchboxRestfulServer.java:33)
        at ca.uhn.fhir.rest.server.RestfulServer.doPost(RestfulServer.java:432)
        at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1921)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.springframework.web.servlet.resource.ResourceUrlEncodingFilter.doFilter(ResourceUrlEncodingFilter.java:67)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:768)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.reflect.InvocationTargetException: null
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:116)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:264)
        ... 50 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "ca.uhn.fhir.validation.ValidationResult.getMessages()" because "result" is null
        at ch.ahdis.fhir.hapi.jpa.validation.ValidationProvider.getOperationOutcome(ValidationProvider.java:291)
        at ch.ahdis.fhir.hapi.jpa.validation.ValidationProvider.validate(ValidationProvider.java:185)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 52 common frames omitted

**Comment by oliveregger** [comment]
powered by matchbox-engine 3.4.2, hapi-fhir 6.8.0 and org.hl7.fhir.core 6.0.22

**Comment by oliveregger** [comment]
issue is 

```json
      "id" : "2f69f609-e3bf-4863-bc42-3cbf0568cab1",
      "extension" : [{
        "url" : "http://hl7.org/fhir/5.0/StructureDefinition/extension-DiagnosticReport.composition",
        "valueReference" : {
          "reference" : "urn:uuid:da065461-34df-4e2e-b69f-4181908575d0",
          "type" : "Composition"
        }
      }],
```

**Comment by oliveregger** [comment]
over the API the following error is transmitted:


  "resourceType": "OperationOutcome",
  "issue": [ {
    "severity": "error",
    "code": "processing",
    "diagnostics": "HAPI-0389: Failed to call access method: java.lang.NullPointerException: Cannot invoke \"ca.uhn.fhir.validation.ValidationResult.getMessages()\" because \"result\" is null"
  } ]
}
