### ISSUE TITLE
FHIR CDA validation problem

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox#136]
validating with adapted clinical CDA model

2023-09-18 19:51:27.107 [http-nio-8080-exec-8] INFO  c.a.matchbox.engine.MatchboxEngine [MatchboxEngine.java:441] Using profile for validation http://hl7.org/fhir/cda/StructureDefinition/Observation|2.1.0-cibuild (2022-11-29T11:55:46+01:00)
Validate Observation against http://hl7.org/fhir/cda/StructureDefinition/Observation|2.1.0-cibuild..........20..2023-09-18 19:51:27.151 [http-nio-8080-exec-8] ERROR c.a.f.h.j.v.ValidationProvider [ValidationProvider.java:230] Ambiguous type IVL_TS ([]) (contact Grahame Grieve for investigation)
org.hl7.fhir.exceptions.FHIRException: Ambiguous type IVL_TS ([]) (contact Grahame Grieve for investigation)
        at org.hl7.fhir.r5.context.BaseWorkerContext.fetchTypeDefinition(BaseWorkerContext.java:2256)
        at org.hl7.fhir.validation.instance.InstanceValidator.isPrimitiveType(InstanceValidator.java:4108)
        at org.hl7.fhir.validation.instance.InstanceValidator.checkChildByDefinition(InstanceValidator.java:5633)
        at org.hl7.fhir.validation.instance.InstanceValidator.checkChild(InstanceValidator.java:5491)
        at org.hl7.fhir.validation.instance.InstanceValidator.validateElement(InstanceValidator.java:5439)
        at org.hl7.fhir.validation.instance.InstanceValidator.startInner(InstanceValidator.java:5091)
        at org.hl7.fhir.validation.instance.InstanceValidator.start(InstanceValidator.java:4884)
        at org.hl7.fhir.validation.instance.InstanceValidator.validateResource(InstanceValidator.java:6347)
        at org.hl7.fhir.validation.instance.InstanceValidator.validate(InstanceValidator.java:908)
        at org.hl7.fhir.validation.instance.InstanceValidator.validate(InstanceValidator.java:742)
        at ch.ahdis.matchbox.engine.MatchboxEngine.validate(MatchboxEngine.java:450)
        at ch.ahdis.fhir.hapi.jpa.validation.ValidationProvider.validateWithResult(ValidationProvider.java:194)
        at ch.ahdis.fhir.hapi.jpa.validation.ValidationProvider.validate(ValidationProvider.java:184)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:264)
        at ca.uhn.fhir.rest.server.method.OperationMethodBinding.invokeServer(OperationMethodBinding.java:399)
        at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.doInvokeServer(BaseResourceReturningMethodBinding.java:146)
        at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.invokeServer(BaseResourceReturningMethodBinding.java:275)
        at ca.uhn.fhir.rest.server.method.OperationMethodBinding.invokeServer(OperationMethodBinding.java:356)
        at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:1190)
        at ch.ahdis.matchbox.MatchboxRestfulServer.handleRequest(MatchboxRestfulServer.java:33)
        at ca.uhn.fhir.rest.server.RestfulServer.doPost(RestfulServer.java:432)
        at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1921)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.springframework.web.servlet.resource.ResourceUrlEncodingFilter.doFilter(ResourceUrlEncodingFilter.java:67)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:768)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:1623)

**Comment by oliveregger** [comment]
solved with #145 cda logical model

**Comment by oliveregger** [comment]
fixed with release 3.4.4
