### ISSUE TITLE
matchbox: provide hl7.fhir.uv.extensions.r4#1.0.0 in classpath

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox#150]
B$$38dfaa02 threw an unhandled Exception: 
ca.uhn.fhir.rest.server.exceptions.ResourceNotFoundException: HAPI-1301: Unable to locate package hl7.fhir.uv.extensions.r4#1.0.0
        at ca.uhn.fhir.jpa.packages.loader.PackageLoaderSvc.fetchPackageFromServerInternal(PackageLoaderSvc.java:85)
        at ca.uhn.fhir.jpa.packages.loader.PackageLoaderSvc.fetchPackageFromPackageSpec(PackageLoaderSvc.java:76)
        at ca.uhn.fhir.jpa.packages.JpaPackageCache.loadPackage(JpaPackageCache.java:510)
        at ca.uhn.fhir.jpa.packages.JpaPackageCache$$FastClassBySpringCGLIB$$fadb1509.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)

**Comment by qligier** [comment]
It should have been loaded with commit e7aed46. What was the configuration used?
