### ISSUE TITLE
IG installation: lenient comparison of 'current' version in dependencies

### ISSUE THREAD

**Issue by qligier** [ahdis/matchbox#229]
When installing an IG that depends on another IG with `current` version, Matchbox could be lenient and continue if any version of that IG is already installed. A warning could be generated for that special case.

Currently, an error is returned, but the IG still appears in the list of installed packages.

Not sure if the validator engine would support that, though. Can it automatically resolve the latest version of the package?

Example: [MeOw](https://build.fhir.org/ig/IHE/pharm-meow/branches/main/index.html) depends on `ihe.domain.logical-datatypes#0.0.1-current`, which has a single version.

<details>
<summary>Failure logs</summary>

```
2024-04-29 19:26:29.044 [main] DEBUG c.a.f.h.j.v.ImplementationGuideProviderR5 [ImplementationGuideProviderR5.java:190] Loading package ihe.pharm.meow#0.1.0 from property hapi.fhir.implementationGuides
2024-04-29 19:26:29.714 [main] INFO  c.u.f.j.p.loader.PackageLoaderSvc [PackageLoaderSvc.java:119] Parsing package .tar.gz (168141 bytes) from https://build.fhir.org/ig/IHE/pharm-meow/branches/main/package.tgz
2024-04-29 19:26:30.159 [main] INFO  o.h.f.u.npm.BasePackageCacheManager [BasePackageCacheManager.java:88] Failed to resolve package ihe.domain.logical-datatypes#current from server: https://packages.fhir.org (Not Found)
2024-04-29 19:26:30.699 [main] INFO  o.h.f.u.npm.BasePackageCacheManager [BasePackageCacheManager.java:88] Failed to resolve package ihe.domain.logical-datatypes#current from server: https://packages2.fhir.org/packages (Not found)
2024-04-29 19:26:30.721 [main] ERROR o.s.boot.SpringApplication [SpringApplication.java:851] Application run failed
ca.uhn.fhir.rest.server.exceptions.ResourceNotFoundException: HAPI-1301: Unable to locate package ihe.domain.logical-datatypes#current
	at ca.uhn.fhir.jpa.packages.loader.PackageLoaderSvc.fetchPackageFromServerInternal(PackageLoaderSvc.java:90)
	at ca.uhn.fhir.jpa.packages.loader.PackageLoaderSvc.fetchPackageFromPackageSpec(PackageLoaderSvc.java:81)
	at ca.uhn.fhir.jpa.packages.JpaPackageCache.loadPackage(JpaPackageCache.java:510)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:385)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717)
	at ca.uhn.fhir.jpa.packages.JpaPackageCache$$SpringCGLIB$$0.loadPackage(<generated>)
	at ch.ahdis.matchbox.util.MatchboxPackageInstallerImpl.fetchAndInstallDependencies(MatchboxPackageInstallerImpl.java:294)
	at ch.ahdis.matchbox.util.MatchboxPackageInstallerImpl.install(MatchboxPackageInstallerImpl.java:204)
	at ch.ahdis.fhir.hapi.jpa.validation.ImplementationGuideProviderR5.load(ImplementationGuideProviderR5.java:154)
	at ch.ahdis.fhir.hapi.jpa.validation.ImplementationGuideProviderR5.loadAll(ImplementationGuideProviderR5.java:203)
	at ch.ahdis.matchbox.spring.MatchboxEventListener.onApplicationEvent(MatchboxEventListener.java:35)
	at ch.ahdis.matchbox.spring.MatchboxEventListener.onApplicationEvent(MatchboxEventListener.java:17)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:149)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:451)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:384)
	at org.springframework.boot.context.event.EventPublishingRunListener.ready(EventPublishingRunListener.java:109)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$ready$6(SpringApplicationRunListeners.java:80)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
	at org.springframework.boot.SpringApplicationRunListeners.ready(SpringApplicationRunListeners.java:80)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:348)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at ca.uhn.fhir.jpa.starter.Application.main(Application.java:36)
```

</details>

**Comment by pvrana** [comment]
We are facing the same problem. Will this be resolved in the near future?

**Comment by oliveregger** [comment]
@pvrana We currently don't have it on the agenda because an ig should not depend on a current version. This will lead to many problems since it is not a reproducable setup. HL7 does not allow to publish IG's which are dependent on current version even if it is technical possible. The IHE guide mentioned above changed later on to use only published version. Can you influence the decision of the dependency?

**Comment by pvrana** [comment]
Thank you for the clarification. We were unaware of this HL7 regulation stating that an IG must not depend on a 'current' version. In light of this information, we will work on updating our IGs to remove these dependencies and ensure full compliance with HL7 requirements.

**Comment by oliveregger** [comment]
@pvrana this are the requirement if you ballot under HL7 International rules (defined by FMG I think). That must not be the case for a country affiliation. However for consistency it would be much better to use versioned dependencies (not current) IG's, just removing the depencies might not work, depending on your profiling.

**Comment by oliveregger** [comment]
can we check what it wouild need to support loading the current version of a dependency? we would also need to check that a current dependen version would get updated when the parent gets updated.
