### ISSUE TITLE
Error on release V1.6.0

### ISSUE THREAD

**Issue by delcroip** [ahdis/matchbox#24]
Thanks for you work,

I tried to launch the v.1.6.0 but it failed (v1.5.0 works)

command I executed

Take v.1.6.0

```
git fetch 
git checkout v1.6.0
```

build the jar
```
mvn clean package -DskipTests
```

rebuild the docker 

```
sudo docker-compose down --rmi local
sudo docker-compose up
```

error message

```
matchbox-test-app    | 2022-01-05 08:42:10.651 [main] ERROR o.s.boot.SpringApplication [?:?] Application run failed
matchbox-test-app    | org.yaml.snakeyaml.constructor.DuplicateKeyException: while constructing a mapping
matchbox-test-app    |  in 'reader', line 21, column 7:
matchbox-test-app    |           cda:
matchbox-test-app    |           ^
matchbox-test-app    | found duplicate key chradorder
matchbox-test-app    |  in 'reader', line 61, column 7:
matchbox-test-app    |           chradorder:
matchbox-test-app    |           ^
matchbox-test-app    |
matchbox-test-app    |  at <unknown class>.processDuplicateKeys(SafeConstructor.java:105)
matchbox-test-app    |  at <unknown class>.flattenMapping(SafeConstructor.java:76)
matchbox-test-app    |  at <unknown class>.constructMapping2ndStep(SafeConstructor.java:189)
matchbox-test-app    |  at <unknown class>.constructMapping(BaseConstructor.java:461)
matchbox-test-app    |  at <unknown class>.construct(SafeConstructor.java:556)
matchbox-test-app    |  at <unknown class>.constructObjectNoCheck(BaseConstructor.java:230)
matchbox-test-app    |  at <unknown class>.constructObject(BaseConstructor.java:220)
matchbox-test-app    |  at <unknown class>.constructObject(OriginTrackedYamlLoader.java:119)
matchbox-test-app    |  at <unknown class>.constructMapping2ndStep(BaseConstructor.java:480)
matchbox-test-app    |  at <unknown class>.constructMapping2ndStep(SafeConstructor.java:190)
matchbox-test-app    |  at <unknown class>.constructMapping(BaseConstructor.java:461)
matchbox-test-app    |  at <unknown class>.construct(SafeConstructor.java:556)
matchbox-test-app    |  at <unknown class>.constructObjectNoCheck(BaseConstructor.java:230)
matchbox-test-app    |  at <unknown class>.constructObject(BaseConstructor.java:220)
matchbox-test-app    |  at <unknown class>.constructObject(OriginTrackedYamlLoader.java:119)
matchbox-test-app    |  at <unknown class>.constructMapping2ndStep(BaseConstructor.java:480)
matchbox-test-app    |  at <unknown class>.constructMapping2ndStep(SafeConstructor.java:190)
matchbox-test-app    |  at <unknown class>.constructMapping(BaseConstructor.java:461)
matchbox-test-app    |  at <unknown class>.construct(SafeConstructor.java:556)
matchbox-test-app    |  at <unknown class>.constructObjectNoCheck(BaseConstructor.java:230)
matchbox-test-app    |  at <unknown class>.constructObject(BaseConstructor.java:220)
matchbox-test-app    |  at <unknown class>.constructObject(OriginTrackedYamlLoader.java:119)
matchbox-test-app    |  at <unknown class>.constructMapping2ndStep(BaseConstructor.java:480)
matchbox-test-app    |  at <unknown class>.constructMapping2ndStep(SafeConstructor.java:190)
matchbox-test-app    |  at <unknown class>.constructMapping(BaseConstructor.java:461)
matchbox-test-app    |  at <unknown class>.construct(SafeConstructor.java:556)
matchbox-test-app    |  at <unknown class>.constructObjectNoCheck(BaseConstructor.java:230)
matchbox-test-app    |  at <unknown class>.constructObject(BaseConstructor.java:220)
matchbox-test-app    |  at <unknown class>.constructObject(OriginTrackedYamlLoader.java:119)
matchbox-test-app    |  at <unknown class>.constructDocument(BaseConstructor.java:174)
matchbox-test-app    |  at <unknown class>.getData(BaseConstructor.java:139)
matchbox-test-app    |  at <unknown class>.getData(OriginTrackedYamlLoader.java:99)
matchbox-test-app    |  at <unknown class>.next(Yaml.java:514)
matchbox-test-app    |  at <unknown class>.process(YamlProcessor.java:198)
matchbox-test-app    |  at <unknown class>.process(YamlProcessor.java:166)
matchbox-test-app    |  at <unknown class>.load(OriginTrackedYamlLoader.java:84)
matchbox-test-app    |  at <unknown class>.load(YamlPropertySourceLoader.java:50)
matchbox-test-app    |  at <unknown class>.load(StandardConfigDataLoader.java:54)
matchbox-test-app    |  at <unknown class>.load(StandardConfigDataLoader.java:36)
matchbox-test-app    |  at <unknown class>.load(ConfigDataLoaders.java:107)
matchbox-test-app    |  at <unknown class>.load(ConfigDataImporter.java:128)
matchbox-test-app    |  at <unknown class>.resolveAndLoad(ConfigDataImporter.java:86)
matchbox-test-app    |  at <unknown class>.withProcessedImports(ConfigDataEnvironmentContributors.java:121)
matchbox-test-app    |  at <unknown class>.processInitial(ConfigDataEnvironment.java:240)
matchbox-test-app    |  at <unknown class>.processAndApply(ConfigDataEnvironment.java:227)
matchbox-test-app    |  at <unknown class>.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:102)
matchbox-test-app    |  at <unknown class>.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:94)
matchbox-test-app    |  at <unknown class>.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:102)
matchbox-test-app    |  at <unknown class>.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:87)
matchbox-test-app    |  at <unknown class>.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
matchbox-test-app    |  at <unknown class>.invokeListener(SimpleApplicationEventMulticaster.java:169)
matchbox-test-app    |  at <unknown class>.multicastEvent(SimpleApplicationEventMulticaster.java:143)
matchbox-test-app    |  at <unknown class>.multicastEvent(SimpleApplicationEventMulticaster.java:131)
matchbox-test-app    |  at <unknown class>.environmentPrepared(EventPublishingRunListener.java:82)
matchbox-test-app    |  at <unknown class>.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:63)
matchbox-test-app    |  at <unknown class>.accept(Unknown Source)
matchbox-test-app    |  at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
matchbox-test-app    |  at <unknown class>.doWithListeners(SpringApplicationRunListeners.java:117)
matchbox-test-app    |  at <unknown class>.doWithListeners(SpringApplicationRunListeners.java:111)
matchbox-test-app    |  at <unknown class>.environmentPrepared(SpringApplicationRunListeners.java:62)
matchbox-test-app    |  at <unknown class>.prepareEnvironment(SpringApplication.java:374)
matchbox-test-app    |  at <unknown class>.run(SpringApplication.java:332)
matchbox-test-app    |  at <unknown class>.run(SpringApplication.java:1343)
matchbox-test-app    |  at <unknown class>.run(SpringApplication.java:1332)
matchbox-test-app    |  at <unknown class>.main(Application.java:32)
matchbox-test-app    |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
matchbox-test-app    |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
matchbox-test-app    |  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
matchbox-test-app    |  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
matchbox-test-app    |  at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
matchbox-test-app    |  at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
matchbox-test-app    |  at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
matchbox-test-app    |  at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

```

**Comment by oliveregger** [comment]
hi @delcroip, thank you for you feedback!

sorry, i commited a configuration which had duplicated implementation guides within and the docker-compose configuration was also not correct. i cleaned it up now that no implementation guide is loaded now.

i commited a fix to the main branch, when you do now the following commands it should work:

```
git checkout main
mvn clean package -DskipTests
docker build -t matchbox .
docker-compose up
```

let me know if you need any further information. i will prepare a new release by end of next week.
