### ISSUE TITLE
FHIR Path validation issue in integration-tests

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox#240]
Validate Patient against http://fhir.ch/ig/ch-elm/StructureDefinition/ChElmPatientInitials|1.3.1...java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
        at org.hl7.fhir.r5.fhirpath.FHIRPathEngine.funcLength(FHIRPathEngine.java:5754)
        at org.hl7.fhir.r5.fhirpath.FHIRPathEngine.evaluateFunction(FHIRPathEngine.java:3975)
        at org.hl7.fhir.r5.fhirpath.FHIRPathEngine.execute(FHIRPathEngine.java:1555)
        at org.hl7.fhir.r5.fhirpath.FHIRPathEngine.execute(FHIRPathEngine.java:1567)
        at org.hl7.fhir.r5.fhirpath.FHIRPathEngine.execute(FHIRPathEngine.java:1567)
        at org.hl7.fhir.r5.fhirpath.FHIRPathEngine.execute(FHIRPathEngine.java:1562)
        at org.hl7.fhir.r5.fhirpath.FHIRPathEngine.execute(FHIRPathEngine.java:1583)
        at org.hl7.fhir.r5.fhirpath.FHIRPathEngine.evaluate(FHIRPathEngine.java:828)

**Comment by oliveregger** [comment]
is a fhir path issue when a primity type is empty but has an extension on it, see https://github.com/ahdis/ch-elm/commit/28ed3f202f92695e5e875672fc66f956760e7b67

**Comment by oliveregger** [comment]
Not expected behaviour per the FHIRPath/FHIR specs - it's a NullPointerException in the core engine, reported and fixed upstream:

- Issue: https://github.com/hapifhir/org.hl7.fhir.core/issues/2558
- Fix PR: https://github.com/hapifhir/org.hl7.fhir.core/pull/2557
- Test cases PR: https://github.com/FHIR/fhir-test-cases/pull/276 (new `primitivesWithoutValue` group in `r5/fhirpath/tests-fhir-r5.xml`)

A primitive that carries only extensions (data-absent-reason) is present in the tree, so `exists()` is true, but it has no value: `hasValue()` is false and `getValue()` is empty (https://hl7.org/fhir/R5/fhirpath.html). `length()` therefore has an empty input and should return empty per FHIRPath, so the invariant evaluates to empty and is reported as a constraint failure - instead of aborting the validation. `FHIRPathEngine.funcLength()` passed the null value straight to `String.length()`; 13 further functions and operators had the same missing guard (`toChars()`, `substring()`, `trim()`, `endsWith()`, `replaceMatches()`, `encode()`, `decode()`, `toDateTime()`, `convertsToBoolean/Date/DateTime/Time()`, `<` `<=` `>` `>=`).

Until the fix is in a core release that matchbox picks up, an invariant can avoid it by guarding with `hasValue()`, which short-circuits before `length()` is reached:

```
family.hasValue() and family.length() = 1
```

The workaround currently in ch-elm (28ed3f2), `('' + family).length() = 1`, avoids the crash for a different reason: `+` concatenates the Java string `"null"`, so the length is 4 and the invariant fails - the right outcome, but by accident.
