### ISSUE TITLE
CH:IPS validation problem

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox#248]
Bundle-UC1-SwissIpsDocument1

2024-06-19 22:02:56.399 [http-nio-8080-exec-3] ERROR c.a.f.h.j.v.ValidationProvider [ValidationProvider.java:200] Error during validation

java.lang.UnsupportedOperationException: null
        at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
        at java.base/java.util.ImmutableCollections$AbstractImmutableCollection.add(ImmutableCollections.java:147)
        at org.hl7.fhir.validation.instance.InstanceValidator.validate(InstanceValidator.java:1008)
        at org.hl7.fhir.validation.instance.InstanceValidator.validate(InstanceValidator.java:834)
        at ch.ahdis.matchbox.engine.MatchboxEngine.validate(MatchboxEngine.java:533)

**Comment by oliveregger** [comment]
fixed in v3.8.6
