### ISSUE TITLE
FHIR Mapping Language: funcMemberOf/resolveValueSet: Not Implemented Yet

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox#49]
Luke: What I’m trying to find something in a Bundle entry where it is in a given valueset so the mapping language piece looks like this:

```
entry.resource : Immunization as immunization
      where vaccineCode.memberOf(http://worldhealthorganization.github.io/ddcc/ValueSet/who-ddcc-vaccines-covid-19)
```

Caused by: java.lang.Error: Not Implemented Yet

                at org.hl7.fhir.r5.utils.structuremap.FFHIRPathHostServices.resolveValueSet(FFHIRPathHostServices.java:99)

                at org.hl7.fhir.r5.utils.FHIRPathEngine.funcMemberOf(FHIRPathEngine.java:4051)

                at org.hl7.fhir.r5.utils.FHIRPathEngine.evaluateFunction(FHIRPathEngine.java:3488)

                at org.hl7.fhir.r5.utils.FHIRPathEngine.execute(FHIRPathEngine.java:1415)

                at org.hl7.fhir.r5.utils.FHIRPathEngine.execute(FHIRPathEngine.java:1427)

                at org.hl7.fhir.r5.utils.FHIRPathEngine.evaluate(FHIRPathEngine.java:722)

                at org.hl7.fhir.r5.utils.FHIRPathEngine.evaluateToBoolean(FHIRPathEngine.java:79

**Comment by oliveregger** [comment]
fixed with version 2.1.0
