### ISSUE TITLE
FHIR Mapping Language tutorial, xml and json issues

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox#51]
https://github.com/ahdis/fhir-mapping-tutorial/blob/master/maptutorial/step1/test.ahdis.ch.http#L34-L35

Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:373)
	at java.base/java.util.ArrayList.get(ArrayList.java:425)
	at org.hl7.fhir.r5.elementmodel.XmlParser.parse(XmlParser.java:230)
	at org.hl7.fhir.r5.elementmodel.XmlParser.parse(XmlParser.java:199)
	at org.hl7.fhir.r5.elementmodel.XmlParser.parse(XmlParser.java:164)
	at org.hl7.fhir.r5.elementmodel.ParserBase.parseSingle(ParserBase.java:110)
	at org.hl7.fhir.r5.elementmodel.Manager.parseSingle(Manager.java:95)
	at ch.ahdis.matchbox.mappinglanguage.StructureMapTransformProvider.transfrom(StructureMapTransformProvider.java:169)
	at ch.ahdis.matchbox.mappinglanguage.StructureMapTransformProvider.manualInputAndOutput(StructureMapTransformProvider.java:160)
	... 54 common frames omitted

**Comment by oliveregger** [comment]
Snapshot was missing when directly uploading the Logical Models through matchbox

**Comment by oliveregger** [comment]
using json instead of xml as source:

022-05-31 16:19:17.357 [http-nio-8080-exec-7] ERROR c.u.f.r.s.i.ExceptionHandlingInterceptor [ExceptionHandlingInterceptor.java:141] Failure during REST processing

ca.uhn.fhir.rest.server.exceptions.InternalErrorException: HAPI-0389: Failed to call access method: org.hl7.fhir.exceptions.FHIRException: Parsing FHIR content returned multiple elements in a context where only one element is allowed

                at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:273)

                at ca.uhn.fhir.rest.server.method.OperationMethodBinding.invokeServer(OperationMethodBinding.java:335)

                at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.doInvokeServer(BaseResourceReturningMethodBinding.java:325)

                at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.invokeServer(BaseResourceReturningMethodBinding.java:432)

                at ca.uhn.fhir.rest.server.method.OperationMethodBinding.invokeServer(OperationMethodBinding.java:310)

                at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:1153)

                at ca.uhn.fhir.jpa.starter.JpaRestfulServer.handleRequest(JpaRestfulServer.java:38)

                at ca.uhn.fhir.rest.server.RestfulServer.doPost(RestfulServer.java:424)

                at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1862)

                at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)

                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)

                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)

                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)

                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)

                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)

                at org.springframework.web.servlet.resource.ResourceUrlEncodingFilter.doFilter(ResourceUrlEncodingFilter.java:67)

                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)

                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)

                at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)

                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)

                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)

                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)

                at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)

                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)

                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)

                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)

                at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)

                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)

                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)

                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)

                at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)

                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)

                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)

                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)

                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)

                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)

                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)

                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)

                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)

                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)

                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)

                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)

                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)

                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)

                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1732)

                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)

                at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)

                at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)

                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

                at java.base/java.lang.Thread.run(Thread.java:833)

Caused by: java.lang.reflect.InvocationTargetException: null

                at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)

                at java.base/java.lang.reflect.Method.invoke(Method.java:577)

                at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:265)

                ... 49 common frames omitted

Caused by: org.hl7.fhir.exceptions.FHIRException: Parsing FHIR content returned multiple elements in a context where only one element is allowed

                at org.hl7.fhir.r5.elementmodel.ParserBase.parseSingle(ParserBase.java:112)

                at org.hl7.fhir.r5.elementmodel.Manager.parseSingle(Manager.java:95)

                at ch.ahdis.matchbox.mappinglanguage.StructureMapTransformProvider.transfrom(StructureMapTransformProvider.java:169)

                at ch.ahdis.matchbox.mappinglanguage.StructureMapTransformProvider.manualInputAndOutput(StructureMapTransformProvider.java:160)

                at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)

                ... 51 common frames omitted

**Comment by oliveregger** [comment]
the json parser (as did the xml parser) does not recognise the logical types, see also https://github.com/ahdis/matchbox/issues/31

**Comment by oliveregger** [comment]
SnapShotGeneration for logcial models takes 15 seconds on test system

**Comment by oliveregger** [comment]
"Invalid request: The FHIR endpoint on this server does not know how to handle POST operation[StructureDefinition] with parameters [[]]"/>

**Comment by oliveregger** [comment]
solved with matchbox 3.1.0
